# @package _global_

model:
  num_heads: 8
  num_layers: 12
  hidden_size: 384
  embedding_dimension: 256
  num_positional_embeddings: 16

optim:
  learning_rate: 3e-5

data:
  primitive_noise:
    enabled: True

max_epochs: 30
num_data_workers: 32
